stages:
  - build-frontend
  - build-backend

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  NODE_VERSION: "18.12.1"

before_script:
  - apt-get update -qy
  - apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install -g @quasar/cli

build-frontend:
  stage: build-frontend
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

build-backend:
  stage: build-backend
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - backend/target/
