variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
  - setup
  - build_frontend
  - build_backend
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target

setup_job:
  stage: setup
  tags:
    - docker
  script:
    - echo "Installing Node.js and npm"
    - apt-get update -qy
    - apt-get install -y nodejs npm

build_frontend_job:
  stage: build_frontend
  tags:
    - docker
  script:
    - echo "Building frontend"
    - cd frontend  # Replace with your frontend directory
    - npm install
    - npm install @quasar/cli -g
    - npm run build
    
build_backend_job:
  stage: build_backend
  tags:
    - docker
  script:
    - echo "Building backend"
    - cd backend
    - mvn package

package_job:
  stage: package
  tags:
    - docker
  script:
    - echo "Maven packaging started"
    - "mvn package"

deploy_job:
  stage: deploy
  tags:
    - docker
  script:
    - echo "Maven deploy started"